language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install --deployment
  - eval "$(ssh-agent -s)"
script:
  - |
      if [ "$TRAVIS_BRANCH" = "master" ];
      then bundle exec rake travis:deploy
      else bundle exec rake build
      fi
branches:
  only:
    - master
    - auto
